from django.urls import path, include
from rest_framework.routers import DefaultRouter

from recipe import views

"""
DefaultRouter generate the urls for my viewset.
E.g.
 1. /api/recipe/tags
 2. /api/recipe/tags/1
 3. /api/recipe/tags/1/[CUSTOM_ACTION]
Automatically registers the appropriate urls for
all actions in my viewset.
"""
router = DefaultRouter()

"""Register viewset with the router"""
router.register('tags', views.TagViewSet)

app_name = 'recipe'

"""Include all of the urls generated by the DefaultRouter"""
urlpatterns = [
  path('', include(router.urls)),
]
